apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: anguda/jenkins:automatic-setup
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: JENKINS_ADMIN_ID
            value: admin
          - name: JENKINS_ADMIN_PASSWORD
            value: admin
          - name: JENKINS_URL
            value: "http://$(HOST_IP):31050"
          - name: AWS_ACCESS_KEY_ID
            value: asdass
          - name: AWS_SECRET_ACCESS_KEY
            value: asdasdsa
          - name: AWS_DEFAULT_REGION
            value: us-west-2
        ports:
        - containerPort: 8080
          name: master
        - containerPort: 50000
          name: slave
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31050
      name: master
    - port: 50000
      targetPort: 50000
      nodePort: 31051
      name: slave 
  type: NodePort
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jenkins-job-setup
spec:
  template:
    spec:
      containers:
      - name: jenkins-job
        image: anguda/jenkins:automatic-setup
        env:
        - name: MY_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: jenkins_url
          value: "http://$(MY_NODE_IP):31050"
        command: ["/bin/sh", "-c"]
        args:
         - cd ~ ;
           wget -q https://raw.githubusercontent.com/angudadevops/jenkins/main/kops-cleanup.xml;
           wget -q https://raw.githubusercontent.com/angudadevops/jenkins/main/kops-incubator.xml;
           crumb=$(curl -s --cookie-jar /tmp/cookies -u admin:admin "$jenkins_url/crumbIssuer/api/json" | jq -r '.crumb');
           jenkins_apikey=$(curl -s -XPOST  -H "Jenkins-Crumb:$crumb" --cookie /tmp/cookies "$jenkins_url/me/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken" --data 'newTokenName=default' --user admin:admin | jq -r '.data.tokenValue');
           echo $jenkins_apikey;
           curl -s -XPOST -k "$jenkins_url/createItem?name=Kops-Incubator" -u admin:$jenkins_apikey --data-binary @kops-incubator.xml -H "Content-Type:text/xml";
           echo " =======================";
           curl -s -XPOST -k "$jenkins_url/createItem?name=Kops-Cleanup" -u admin:$jenkins_apikey --data-binary @kops-cleanup.xml -H "Content-Type:text/xml";
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'echo Waiting for jenkins server become ready! && sleep 30']
      restartPolicy: OnFailure
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
